.TH SORTDEMO 1 "August 8, 2020" 1.1 sortdemo \" -*- nroff -*-
.SH NAME
sortdemo \- A sort method demonstration program for wxWidgets

.SH SYNOPSIS


.SH DESCRIPTION

sortdemo is an X11 GUI application, based on wxWidgets, that demonstrates
various sort algorithms visually.


.SH USAGE
sortdemo

There are no command arguments


